### ISSUE TITLE
中文乱码有遇到过吗

### ISSUE THREAD

**Issue by i542873057** [infopensource/WechatBot#2]
发送中文文本，调用send_msg 微信里面显示乱码

**Comment by infopensource** [comment]
功能没有问题，有人遇到过说是因为网页请求的字符带了&amp;#xFEFF



---原始邮件---
发件人: "ShaoJianan"<notifications@github.com&gt;
发送时间: 2020年4月7日(周二) 中午12:35
收件人: "infopensource/WechatBot"<WechatBot@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [infopensource/WechatBot] 中文乱码有遇到过吗 (#2)




 
发送中文文本，调用send_msg 微信里面显示乱码

**Comment by i542873057** [comment]
> 功能没有问题，有人遇到过说是因为网页请求的字符带了&amp;#xFEFF
> […](#)
> ---原始邮件--- 发件人: "ShaoJianan"<notifications@github.com&gt; 发送时间: 2020年4月7日(周二) 中午12:35 收件人: "infopensource/WechatBot"<WechatBot@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [infopensource/WechatBot] 中文乱码有遇到过吗 (#2) 发送中文文本，调用send_msg 微信里面显示乱码 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

问题已经解决，对于非unicode程序需要在系统中开启对应的中文支持。。一般都是默认开启的，我这台是美国服务器没开，踩了个坑

**Comment by i542873057** [comment]
另外 想问下，有什么办法能防止被封吗，今天运行了一会儿，微信就被封了

**Comment by infopensource** [comment]
这个我不清楚...因为我现在还没出现过这种情况...



---原始邮件---
发件人: "ShaoJianan"<notifications@github.com&gt;
发送时间: 2020年4月8日(周三) 中午1:40
收件人: "infopensource/WechatBot"<WechatBot@noreply.github.com&gt;;
抄送: "infopensource"<2223513246@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [infopensource/WechatBot] 中文乱码有遇到过吗 (#2)




 
另外 想问下，有什么办法能防止被封吗，今天运行了一会儿，微信就被封了
